package versiondisclosure

import (
	"fmt"
	"net/http"

	"github.com/subzerodev/hive/handlers"
)

func init() {
	handlers.Register(func() {
		handlers.Handle("/vulns/info-disclosure/version-disclosure/server-headers", serverHeaders)
		handlers.Handle("/vulns/info-disclosure/version-disclosure/comments", comments)
		handlers.Handle("/vulns/info-disclosure/version-disclosure/fp/hidden", fpHidden)
	})
}

func serverHeaders(w http.ResponseWriter, r *http.Request) {
	// VULNERABLE: Expose version info in headers
	w.Header().Set("Server", "Apache/2.4.51 (Ubuntu)")
	w.Header().Set("X-Powered-By", "PHP/7.4.3")
	w.Header().Set("X-AspNet-Version", "4.0.30319")
	w.Header().Set("X-AspNetMvc-Version", "5.2.7")
	w.Header().Set("Content-Type", "text/html")

	fmt.Fprintf(w, `<!DOCTYPE html>
<html>
<head><title>Version Disclosure - Headers</title></head>
<body>
<h1>Server Information</h1>
<p>Check the response headers (use browser DevTools or curl -v)</p>
<h2>Headers Being Sent:</h2>
<ul>
    <li>Server: Apache/2.4.51 (Ubuntu)</li>
    <li>X-Powered-By: PHP/7.4.3</li>
    <li>X-AspNet-Version: 4.0.30319</li>
    <li>X-AspNetMvc-Version: 5.2.7</li>
</ul>
<p><small>VULNERABLE: Server version info in response headers</small></p>
</body></html>`)
}

func comments(w http.ResponseWriter, r *http.Request) {
	w.Header().Set("Content-Type", "text/html")
	// VULNERABLE: Version info in HTML comments
	fmt.Fprintf(w, `<!DOCTYPE html>
<html>
<!-- Generated by WordPress 5.8.1 -->
<!-- Theme: TwentyTwenty v1.8 -->
<!-- jQuery v3.5.1 loaded -->
<head>
    <title>Version Disclosure - Comments</title>
    <!-- Debug: PHP 7.4.3, MySQL 8.0.26 -->
</head>
<body>
<h1>Website Content</h1>
<p>View page source to see version info in HTML comments.</p>
<!-- TODO: Remove debug comments before production -->
<!-- API Version: 2.3.1 -->
<!-- Last modified: 2024-01-15 by admin -->
<p><small>VULNERABLE: Version info exposed in HTML comments</small></p>
</body></html>`)
}

func fpHidden(w http.ResponseWriter, r *http.Request) {
	// SAFE: No version info exposed
	w.Header().Set("Server", "")
	w.Header().Set("X-Content-Type-Options", "nosniff")
	w.Header().Set("Content-Type", "text/html")

	fmt.Fprintf(w, `<!DOCTYPE html>
<html>
<head><title>Version Hidden</title></head>
<body>
<h1>Secure Server</h1>
<p>No version information is exposed in headers or content.</p>
<p><small>SAFE: Version information properly hidden</small></p>
</body></html>`)
}
